config/routes.rb
Athcli2::Application.routes.draw do
  post 'requests/:id/add_request_comment' => 'requests#add_request_comment', as: :add_request_comment
  get 'requests/request_reload' => 'requests#request_reload', as: :request_reload
  get "home/index"
  get "home/coach_index"
  get "home/user_index"
    root "home#index"
  resources :requests
  get 'requests/:id/scenes' => 'requests#scenes', as: :request_scenes
  devise_for :coaches
  devise_for :users

end

app/models/coach.rb
class Coach < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :requests
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :coach
	belongs_to :user
	belongs_to :scene
end

app/models/request.rb
class Request < ActiveRecord::Base
	belongs_to :user
	belongs_to :coach
	has_many :scenes

	has_attached_file :movie,
	  								:storage => :s3,
	                  :s3_credentials => "#{Rails.root}/config/aws.yml",
	                  :path => ":class/:attachment/:id/:style/:filename",
	                  :url => ':s3_domain_url'
end

app/models/scene.rb
class Scene < ActiveRecord::Base
	belongs_to :user
	belongs_to :request
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :comments
         has_many :requests
         has_many :scenes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)

    if resource.is_a?(Coach)
        home_coach_index_path

  	else
        home_user_index_path
    end

    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def coach_index
  	authenticate_coach!
  	@requests = current_coach.requests
  end

  def user_index
  	authenticate_user!
  	@requests = current_user.requests
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy, :scenes, :add_request_comment]
  before_action :authenticate_user!, only: [:create, :new, :update, :destroy]
  before_action :permission_ok, only: [:show, :update, :edit, :update, :destroy, :scenes, :add_request_comment]
  # GET /requests
  # GET /requests.json
  def index
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
    if current_coach
      @scenes = @request.scenes
    elsif current_user
      redirect_to request_scenes_path
    end
  end


  def request_reload
    authenticate_coach!
    #check if user can access
    if Request.find(params[:request_id]) &&  Request.find(params[:request_id]).coach == current_coach
      @scene = Scene.create(:request_id => params[:request_id], :image_url => params[:imgurl], :timestamp => params[:timestamp])
      Comment.create(:scene_id => @scene.id, :comment => params[:comment], :coach_id => params[:coach], :user_id => params[:user]) unless params[:comment].blank?
      @request = Request.find params[:request_id]
      @scenes = @request.scenes
      respond_to do |format|
        format.js { 
          render 'requests/update_scenes' and return
        }
      end
    else
      redirect_to root_path, notice: "Bad request." and return
    end  
  end


  def add_request_comment
    if current_coach
      Comment.create(:scene_id => params[:comments][:scene_id], :comment => params[:comments][:comment], :coach_id => current_coach.id)
    elsif current_user
      Comment.create(:scene_id => params[:comments][:scene_id], :comment => params[:comments][:comment], :user_id => current_user.id)
    end

    redirect_to request.referer
  end

  def scenes
    @scenes = @request.scenes
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)
    @request.user = current_user
    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render action: 'show', status: :created, location: @request }
      else
        format.html { render action: 'new' }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_request
    @request = Request.find(params[:id])
  end

  # Could be used to create thumbnails from uploaded videos.
  require 'streamio-ffmpeg'
  def thumbnail path, second
    movie = FFMPEG::Movie.new(path)
    return movie.screenshot("tmp/#{File.basename(path)}.jpg", :seek_time => second)
  end


  def permission_ok
    if current_coach && @request.coach_id == current_coach.id
    elsif current_user && @request.user_id == current_user.id
    else
      redirect_to root_path, notice: "Bad request."
    end
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def request_params
    params.require(:request).permit(:title, :movie_url, :user_id, :coach_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/home/coach_index.html.erb
<div class="text-danger">
<h1> <%= current_coach.email %>'s profile</h1>
</div>

<h3>Your Requests</h3>
<ul class="nav nav-pills nav-stacked">
<% @requests.each do |request| %>
<li>
<%= link_to request.title, request_path(request) %>
</li>
<%end%>
</ul>

app/views/home/index.html.erb
<h1>Athcli</h1>
<br/>
<p><%=link_to "User Login", new_user_session_path, class: "btn btn-success" %></p>
<p><%=link_to "Coach Login", new_coach_session_path,  class: "btn btn-warning"  %></p>

app/views/home/user_index.html.erb
<h1 class="text-danger"> <%= current_user.email %>'s profile</h1>


<%=link_to "New Request", new_request_path, class: "btn btn-success" %>

<ul class="nav nav-pills nav-stacked">
<h2>Your Requests</h2>
<% @requests.each do |request| %>
<li>
<%= link_to request.title, request_path(request) %>
</li>
<%end%>
</ul>

app/views/layouts/_video.html.erb
<video width="480" crossorigin="anonymous" id="v" controls="" class="img-responsive">  
  <source src="<%= @request.movie_url %>" type="video/mp4"> 
  Format not supported
</video> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vaton</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body data-controller="<%= controller_name %>" data-action="<%= action_name %>">

 <div class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <% if user_signed_in? %>
          <%= link_to "Vaton", home_user_index_path, class: "navbar-brand" %>
          <% end %>
          <% if coach_signed_in? %>
          <%= link_to "Vaton", home_coach_index_path, class: "navbar-brand" %>
          <% end %>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav navbar-right">
            <li><% if user_signed_in? %>
            <%= link_to "Logged in as #{current_user.email}. Logout", destroy_user_session_path, method: :delete %>
            <% end%>
            </li>
            <li>
            	<% if coach_signed_in? %>
              <%= link_to "Logged in as #{current_coach.email}. Logout", destroy_coach_session_path, method: :delete %>
              <% end%>
            </li>
          </ul>

        </div>
      </div>
    </div>

<div class="clearfix"></div>
<div class="container">
<% if notice %>
<div class="alert alert-info"><%= notice %></div>
<%end%>


<%= yield %>
</div>
</body>
</html>

app/views/requests/_form.html.erb
<%= simple_form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :title %>
  </div>
  <div class="field">
    <%= f.input :movie_url %><br>
  </div>
  <div class="field">
    <%= f.input :coach_id, collection: Coach.all, :include_blank => false, label_method: lambda { |obj| "#{obj.email}" } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/_scenes_partial.html.erb
<h1>Scenes for <%= @request.title %> <span class="badge"><%= @scenes.count %></span></h1>

<% @scenes.each_with_index do |scene, i| %>
  
  <div class="row">
    <div class="col-sm-4 scene-image">
      <a href="#" class="thumbnail">
        <%= image_tag(scene.image_url) %>
      </a>
    </div>
  
    <div class="col-sm-8 scene-info">
      <h3>Scene number #<%=i%><span class="badge"> Time: <%= scene.timestamp.to_f.round(2) %></span></h3>
      <h3>Comments</h3>
      <% scene.comments.each do |c| %>
      <div class="triangle-isosceles <%= 'top'.html_safe if c.user_id %>"><%= c.comment %></div>
      <% end %>
    </div>
    
  </div>

<%end%>

app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %>

app/views/requests/index.html.erb
<h1>Listing requests</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Movie url</th>
      <th>User</th>
      <th>Coach</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.title %></td>
        <td><%= request.movie_url %></td>
        <td><%= request.user_id %></td>
        <td><%= request.coach_id %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New request</h1>

<%= s3_uploader_form callback_url: requests_url,
  id: "s3_uploader",
  acl: "private",
  callback_param: "direct_upload_url",
  max_file_size: 40.megabytes do %>
  <%= file_field_tag :file, multiple: false %>
<% end %>
<br/>
 
 
<div id="uploads_container"></div>
<script id="template-upload" type="text/x-tmpl">
<div id="upload_{%=o.unique_id%}" class="upload">
  <h5>{%=o.name%}</h5>
  <div class="progress progress-striped active"><div class="bar" style="width: 0%"></div></div>
</div>
</script>
<br/>

<%= render 'form' %>

app/views/requests/scenes.html.erb
<h1>Scenes for <%= @request.title %> <span class="badge"><%= @scenes.count %></span></h1>
<div class="row">
<div class="col-md-6">
    <%= render 'layouts/video' %>
</div>
</div>

<% @scenes.each_with_index do |scene, i| %>
  
  <div class="row">
    <div class="col-sm-4 scene-image">
      <a href="#" class="thumbnail">
        <%= image_tag(scene.image_url) %>
      </a>
    </div>
  
    <div class="col-sm-8 scene-info">
      <h3>Scene number #<%=i%></h3>
      <h3>Comments</h3>
      <% scene.comments.each do |c| %>
      <div class="triangle-isosceles <%= 'top'.html_safe if c.user_id %>"><%= c.comment %></div>
      <% end %>

      <br/>

      <%= simple_form_for :comments, { url: add_request_comment_path, :method => 'post' } do |f| %>
        <%= f.input :comment, as: :text, placeholder: "Leave comment", :input_html => { :class => "form-control" } %>
        <%if current_coach %>
          <%= f.input :coach_id, :as => :hidden, :input_html => { :value => "#{@request.coach_id}" } %>
        <%elsif current_user %>
          <%= f.input :user_id, :as => :hidden, :input_html => { :value => "#{@request.user_id}" } %>
        <%end%>
        <%= f.input :scene_id, as: :hidden, :input_html => { :value => "#{scene.id}" } %>
        <%= f.button :submit, "Submit", class: "btn btn-success submit" %>
      <% end %>
    </div>
  </div>

<%end%>

app/views/requests/show.html.erb
<h1>  <%= @request.title %> for 
  <%= @request.coach.email if @request.coach %>
 <br/></h1> <br/>
<input type="hidden" id="request_id" value=<%="#{@request.id}"%>>
<div id="request_modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <h4>Uploading the scene.</h4>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="row coach-container">
  <div class="col-md-6">
    <%= render 'layouts/video' %>
    <button id="snap" class="btn btn-success">Take screenshot</button>
  </div>
  <div class="col-md-6">
    <div id="l" class="literally">
    	<canvas id="b"></canvas>
    	<canvas id="c"></canvas>
    </div>
    <br>
    <div class="form-group">
      <label for="comment">Comment</label>
      <input type="text" class="form-control comment-input" id="comment_box" placeholder="Enter comment">
      <input type="hidden" id="coach" placeholder="Enter comment" value="<%= @request.coach_id %>">
      <input type="hidden" id="user" placeholder="Enter comment" value="<%= @request.coach_id %>">
    </div>
    <form id="<%= IMGUR_CLIENT_ID %>" class="imgur-submit">
        <input type="submit" class="btn btn-submit" id="imgur" value="Save Scene">
        <input class="scene_url" type="hidden">
    </form>
  </div>
</div>







<%if user_signed_in? && @request.user == current_user %> 
<%= link_to 'Edit', edit_request_path(@request), class: "btn btn-warning" %> 

<%end%>

<div id = "scenes_list">
<hr/>
<h2>Scenes <%= link_to "All Scenes for this request", request_scenes_path(@request), class: "btn btn-warning" %></h2>
<%= render 'scenes_partial' %>
</div>

app/views/requests/update_scenes.js.erb
$("#scenes_list").html("<%= escape_javascript(render(:partial => "scenes_partial"))%>");